---
language: shell
os: linux
dist: bionic
services: docker
env:
  global:
    - HADOLINT_VERSION=1.18.0
  jobs:
    - distribution: centos
      version: 8
    - distribution: centos
      version: 7
    - distribution: debian
      version: 10
    - distribution: ubuntu
      version: 20.04
    - distribution: ubuntu
      version: 18.04
    - distribution: ubuntu
      version: 16.04
    - distribution: fedora
      version: 32
    - distribution: fedora
      version: 31
    - distribution: fedora
      version: 30
    - distribution: fedora
      version: 29
# before_install:
#   - sudo curl -L https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint
#   - sudo chmod 755 /usr/local/bin/hadolint
#   - hadolint travis-Dockerfile.${distribution}${version}
install:
  - docker pull ${distribution}:${version}
  - docker build --no-cache --rm --file=travis/Dockerfile.${distribution}${version} --tag=${distribution}${version}:travis travis
script:
  - container_id=$(mktemp)
  - docker run --detach --privileged --cap-add=ALL -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /lib/modules:/lib/modules:ro ${distribution}${version}:travis > "${container_id}"
  - docker exec "$(cat ${container_id})" ansible localhost -m ping
  - docker rm -f "$(cat ${container_id})"
after_success:
  - docker tag ${distribution}${version}:travis quay.io/aminvakil/docker-${distribution}${version}-ansible
  - docker login quay.io -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD"
  - docker push quay.io/aminvakil/docker-${distribution}${version}-ansible
