FROM ubuntu:focal

LABEL maintainer="Amin Vakil <info@aminvakil.com>"

ENV container docker
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       python3-setuptools \
       python3-pip \
       python3-wheel \
       systemd \
       sudo \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean

RUN pip3 install ansible

ENTRYPOINT ["/bin/systemd"]
